version: 0.2

phases:
  build:
    commands:
      - echo "Récupération de l'instance EC2 via tag..."
      - |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=kle-codebuild-test" "Name=tag:environment,Values=dev" \
          --query "Reservations[].Instances[].InstanceId" \
          --output text \
          --region eu-west-3)

        echo "Résultat brut $INSTANCE_ID"

        # Vérifie si aucun ID trouvé
        if [ -z "$INSTANCE_ID" ]; then
          echo "Aucune instance trouvée pour les tags spécifiés."
          exit 1
        fi

        # Vérifie si plusieurs IDs trouvés
        if [ $(echo "$INSTANCE_ID" | wc -w) -gt 1 ]; then
          echo "Plusieurs instances trouvées : $INSTANCE_ID"
          echo "Merci de préciser des tags uniques ou d'affiner le filtre."
          exit 1
        fi

        echo "Instance trouvée $INSTANCE_ID"
