version: 0.2

env:
  git-credential-helper: yes

phases:
  build:
    commands:
      - echo "S3_BUCKET_PATH=$S3_BUCKET_PATH"
      - echo "GIT_TAG_VERSION=$GIT_TAG_VERSION"
      - echo "ARTIFACT_FOLDER_NAME=$ARTIFACT_FOLDER_NAME"
      - echo "GIT_TAG_VERSION=$GIT_TAG_VERSION"

      - echo "le commit actuel correspond-il à un tag"
      - git fetch --tags
      - echo "Searching tag for current commit..."
      - TAG=$(git tag --points-at HEAD)
      - | 
        if [ -z "$TAG" ]; then
          echo "ERROR: Ce commit n'est associé à aucun tag. Interruption du pipeline.";
          exit 1;
        fi
        echo "Tag trouvé: $TAG"

      - echo "Création du dossier ${ARTIFACT_FOLDER_NAME}"
      - mkdir /tmp/artifact/${ARTIFACT_FOLDER_NAME}

      - echo "Copie du contenu dans ${ARTIFACT_FOLDER_NAME}/"
      - cp -R . /tmp/artifact/${ARTIFACT_FOLDER_NAME}/

      - echo "Création du ZIP artifact.zip"
      - zip -r artifact_${TAG}.zip /tmp/artifact/

      - |
        echo "Upload du ZIP dans S3..."
        S3_BUCKET="$S3_BUCKET_PATH"
        S3_PREFIX="mon/dossier/cible"
        DEST="s3://${$S3_BUCKET_PATH}/artifact_${TAG}.zip"
        aws s3 cp artifact_${TAG}.zip "${DEST}"
        
        