version: 0.2

env:
  git-credential-helper: yes

phases:
  build:
    commands:
      - echo "S3_BUCKET_PATH=$S3_BUCKET_PATH"
      - echo "GIT_TAG_VERSION=$GIT_TAG_VERSION"
      - echo "ARTIFACT_FOLDER_NAME=$ARTIFACT_FOLDER_NAME"
      - echo "GIT_TAG_VERSION=$GIT_TAG_VERSION"
      - PACKAGE_DIR=/tmp/artifact/${ARTIFACT_FOLDER_NAME}/
      - PACKAGE_ROOT_DIR=/tmp/artifact
      - echo "le commit actuel correspond-il à un tag"
      - git fetch --tags
      - echo "Searching tag for current commit..."
      - TAG=$(git tag --points-at HEAD)
      - | 
        if [ -z "$TAG" ]; then
          echo "ERROR: Ce commit n'est associé à aucun tag. Interruption du pipeline.";
          exit 1;
        fi
        echo "Tag trouvé: $TAG"

      - echo "Création du dossier ${PACKAGE_DIR}"
      - mkdir -p ${PACKAGE_DIR}

      - echo "Copie du contenu dans ${PACKAGE_DIR}"
      - cp -R * ${PACKAGE_DIR}

      - echo "Création du ZIP artifact.zip"
      - zip -r artifact_${TAG}.zip ${PACKAGE_ROOT_DIR}

      - echo "Upload du ZIP dans S3..."
      - DEST="s3://${S3_BUCKET_PATH}/artifact_${TAG}.zip"
      - echo "DEST=$DEST"
      - aws s3 cp artifact_${TAG}.zip "${DEST}"
        
        