version: 0.2

phases:
  build:
    commands:
      - echo "Récupération de l'instance EC2 via tag..."
      - |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=kle-codebuild-test" "Name=tag:environment,Values=dev"\
          --query "Reservations[].Instances[].InstanceId" \
          --output text \
          --region eu-central-1)

        echo "Résultat brut $INSTANCE_ID"

        # Vérifie si aucun ID trouvé
        if [ -z "$INSTANCE_ID" ]; then
          echo "Aucune instance trouvée pour les tags spécifiés."
          exit 1
        fi

        # Vérifie si plusieurs IDs trouvés
        if [ $(echo "$INSTANCE_ID" | wc -w) -gt 1 ]; then
          echo "Plusieurs instances trouvées : $INSTANCE_ID"
          echo "Merci de préciser des tags uniques ou d'affiner le filtre."
          exit 1
        fi

        echo "Instance trouvée $INSTANCE_ID"

      - echo "CODEBUILD_SOURCE_VERSION = $CODEBUILD_SOURCE_VERSION"
      # Si CODEBUILD_SOURCE_VERSION est un ARN complet
      - OBJECT_KEY=$(echo $CODEBUILD_SOURCE_VERSION | awk -F':::' '{print $2}')
      - echo "Object key $OBJECT_KEY"
      # Téléchargement du fichier depuis S3
      - aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Déploiement du fichier" \
          --parameters 'commands=[
              "mkdir -p /tmp/uploaded /tmp/monapp"
              "aws s3 cp s3://'"$OBJECT_KEY"' /tmp/uploaded/fichier.zip",
              "unzip -o /tmp/uploaded/fichier.zip -d /tmp/monapp"
          ]'